### ISSUE TITLE
Trigger deployment workflow

### ISSUE THREAD

**Issue by nickfarrow** [unspentspace/unspent.space#13]
Wondering how this github action works? Is it possible for me to deploy? I suppose it is something different to "rerun all jobs".

Maybe it's just a permissions thing, and I would usually see it on the Actions page.

**Comment by dragon-foobar** [comment]
hmm... good question. At the moment, anyone with the right permissions can trigger the github action for gh-pages to deploy to the site. Have a look at this doc after the Installing heading: https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/how-gatsby-works-with-github-pages/

**Comment by unspentspace-admin** [comment]
@nickfarrow you should have required permissions in this repo now. All down from your local command line.

**Comment by nickfarrow** [comment]
Nice! Running `yarn run deploy` worked for me,
Thanks guys!
